### PR TITLE
ENH: Add commit ID when downloading CXR-BERT model

### LINKED ISSUE #481: Specify commit hash when downloading multimodal model weights
A warning is shown when downloading models from Hugging Face:

```text
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
```

We need to specify the `revision` for security.

### PR DESCRIPTION
**Pull request by ozan-oktay**
Use the "commit hash" to pull the CXR-BERT model from HuggingFace Hub.

Closes #481

### CODE REVIEW

**Comment by fepegar** [comment]
I've re-run the security check, it looks unrelated.

The error in the notebook happens because it's installing the code in `main` but trying to use the module introduced in this PR. We can ignore that as it's independent of this PR. I'll open an issue.

**Review by fepegar — APPROVED** [review]

**Comment by fepegar** [comment]
Shall we merge this? The failing tests are unrelated.

**Comment by ozan-oktay** [comment]
> Shall we merge this? The failing tests are unrelated.

Yes, I agree, I think we can go ahead.

**Comment by fepegar** [comment]
Checks now pass thanks to

- #490 
- #492

**Pull request merged**
