### PR TITLE
DOC: Add Codecov badge to README

### PR DESCRIPTION
**Pull request by fepegar**
It looks like this:

[codecov](https://codecov.io/gh/microsoft/hi-ml)

### CODE REVIEW

**Comment by fepegar** [comment]
@ant0nsc do you know why Codecov might be reporting a large difference in coverage for this? Also, why is coverage uploaded twice in the build workflow? I missed that in the PR.

https://github.com/microsoft/hi-ml/blob/7ddb45d04a46b73d811792b65230a21c787ba9bf/.github/workflows/build-test-pr.yml#L207-L211

https://github.com/microsoft/hi-ml/blob/7ddb45d04a46b73d811792b65230a21c787ba9bf/.github/workflows/build-test-pr.yml#L262-L266

**Comment by fepegar** [comment]
Apparently, the difference shown here might have been "[a timing issue](https://community.codecov.com/t/codecov-reporting-impacted-files-for-unchanged-and-completely-unrelated-file/2635/2)".

**Comment by ant0nsc** [comment]
@fepegar , Uploading is happening twice because first we do it for hi-ml and hi-ml-azure (matrix), and then in line 262 for the histo folder. However... For this run, there is no sign of results from hi-ml-azure? 
image

**Comment by fepegar** [comment]
Thanks for clarifying. No idea why that happened! It looks ok for more recent commits.

**Review by ant0nsc — APPROVED** [review]

**Review by mebristo — APPROVED** [review]

**Pull request merged**
