### PR TITLE
ENH: Add Credential Scanning Workflow

### PR DESCRIPTION
**Pull request by ant0nsc**
Adding a credential scanner also as a github workflow because we have had issues with the ADO-based one.

### CODE REVIEW

**Comment by ant0nsc** [comment]
Closing until we have more information about this action.

**Comment by ant0nsc** [comment]
Closing until clarifications available here: https://github.com/microsoft/security-devops-action/issues/21

**Review by kenza-bouzid — APPROVED** [review]
LGTM in general. Should we worry about Code Scanning warning raised in Dokerfile and config_loader?

**Comment by ant0nsc** [comment]
> LGTM in general. Should we worry about Code Scanning warning raised in Dokerfile and config_loader?

Thanks for the reminder. I've addressed all alerts and added relevant comments

**Review by peterhessey — APPROVED** [review]

**Pull request merged**
